services:
  - type: web
    name: evobuz-vendor-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vendors.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
